### ISSUE TITLE
Nav tag should be in the header tag

### ISSUE THREAD

**Issue by audukehinde** [mwanawabangona/mobile-version-2#3]
This is a nice code but please place the nav tag in the header tag 👍 . Doing this means you are following HTML best practices and this should be encouraged. 
![elis](https://user-images.githubusercontent.com/88510160/134130934-35f9b814-c123-4878-bfbe-46a6d3836390.PNG)

**Comment by mwanawabangona** [comment]
Good eye! I missed that thank you... Will have it done thank you!
