### ISSUE TITLE
Duplicate selector

### ISSUE THREAD

**Issue by ntazelo** [mwanawabangona/mobile-version-2#5]
You did a great job 👍  but there are still issues with your linters please removed duplicate selectors in your CSS code. Duplicate selectors add conflicts into your CSS code.
![screenshot (3)](https://user-images.githubusercontent.com/52507134/134135442-b4230c5d-1a14-46cd-b875-1616422b6348.png)

**Comment by mwanawabangona** [comment]
Thank you for noticing that Error, however I corrected it thank you!
